### ISSUE TITLE
IITC-Mobile crashes at Google authentication

### ISSUE THREAD

**Issue by sdhnewman** [HubertZhang/IITC-Scripts#1]
Hi. In iOS 12.2 public beta 4 (16E5212f), the app crashes immediately after tapping the sign-in button for Google Authentication. This is new with this iOS beta build: no issues in previous public betas.
I tried HSiIITC for a comparison (only, because IITC-Mobile is way better) and it was able to authenticate me with the Google.

**Comment by HubertZhang** [comment]
Sorry for late reply, if you are still encountering similar problem please discuss them in https://t.me/iitc_mobile_group 😅

**Comment by sdhnewman** [comment]
Problem gone. Sorry, I forgot that I had submitted the issue!  :)
